import copy
import random


class Node:
    def __init__(self, state=None, parent=None, action=None):
        self.state = state
        self.parent = parent
        self.action = action


class Problem:
    def __init__(self, initial, goal):
        self.initial = initial
        self.goal = goal

    def find_zero(self, board):
        for i in range(3):
            for j in range(3):
                if board[i][j] == 0:
                    return i, j
        return None

    def actions(self, state):
        i, j = self.find_zero(state)
        moves = []
        if j > 0:
            moves.append("Left")
        if j < 2:
            moves.append("Right")
        if i > 0:
            moves.append("Up")
        if i < 2:
            moves.append("Down")
        random.shuffle(moves)
        return moves

    def result(self, state, action):
        i, j = self.find_zero(state)
        if action == "Left":
            ni, nj = i, j - 1
        elif action == "Right":
            ni, nj = i, j + 1
        elif action == "Up":
            ni, nj = i - 1, j
        elif action == "Down":
            ni, nj = i + 1, j
        else:
            return None
        new_state = copy.deepcopy(state)
        new_state[i][j], new_state[ni][nj] = new_state[ni][nj], new_state[i][j]
        return new_state

    def goal_test(self, state):
        return state == self.goal


def manhattan_distance(state, goal):
    distance = 0
    goal_pos = {}
    for i in range(3):
        for j in range(3):
            goal_pos[goal[i][j]] = (i, j)

    for i in range(3):
        for j in range(3):
            tile = state[i][j]
            if tile != 0:
                goal_i, goal_j = goal_pos[tile]
                distance += abs(i - goal_i) + abs(j - goal_j)

    return distance


def value(state, goal):
    return -manhattan_distance(state, goal)


def print_state(state):
    for row in state:
        print(row)
    print("---")


def random_state_from(problem, steps=20):
    current = copy.deepcopy(problem.initial)
    for _ in range(steps):
        action = random.choice(problem.actions(current))
        current = problem.result(current, action)
    return current


def Random_Restart_Hill_Climbing(problem, max_restart=30, random_steps=20):
    """
    Random Restart Hill Climbing for 8-puzzle.
    - Heuristic: Manhattan distance (value = -Manhattan).
    - Each restart starts from a random state generated by random moves from initial.
    - Always picks the best neighbor among better neighbors (ties broken randomly).
    """

    for restart in range(1, max_restart + 1):
        current_state = random_state_from(problem, random_steps)
        current_node = Node(state=current_state)
        current_value = value(current_node.state, problem.goal)
        path = [current_node]

        while True:
            if problem.goal_test(current_node.state):
                actions = []
                states = []
                for node in path:
                    states.append(node.state)
                    if node.action is not None:
                        actions.append(node.action)
                return actions, states, True, restart

            better_neighbors = []
            for action in problem.actions(current_node.state):
                next_state = problem.result(current_node.state, action)
                next_value = value(next_state, problem.goal)
                if next_value > current_value:
                    better_neighbors.append((next_value, action, next_state))

            if not better_neighbors:
                break

            best_value = max(n[0] for n in better_neighbors)
            best_candidates = [n for n in better_neighbors if n[0] == best_value]
            next_value, action, next_state = random.choice(best_candidates)

            next_node = Node(state=next_state, parent=current_node, action=action)
            current_node = next_node
            current_value = next_value
            path.append(current_node)

    return None, None, False, max_restart


if __name__ == "__main__":
    initial = [
        [2, 8, 3],
        [1, 6, 4],
        [7, 0, 5]
    ]

    goal = [
        [1, 2, 3],
        [8, 0, 4],
        [7, 6, 5]
    ]

    problem = Problem(initial, goal)

    actions, states, found, restarts = Random_Restart_Hill_Climbing(
        problem,
        max_restart=50,
        random_steps=25
    )

    print("=" * 55)
    print("  8-PUZZLE RANDOM RESTART HILL CLIMBING")
    print("=" * 55)
    print(f"Restarts used: {restarts}")

    if not found:
        print("\nNo solution found (local maxima across all restarts).")
    else:
        print(f"\nSolution length: {len(actions)}")
        print("Actions:", " -> ".join(actions))
        print("\nStates:")
        for idx, state in enumerate(states):
            if idx == 0:
                print(f"Step {idx} (Start):")
            else:
                print(f"Step {idx} ({actions[idx - 1]}):")
            print_state(state)
